name: Rust Nightly Release

on:
  push:
    branches: [ "main" ]
    tags: [ "[0-9]*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            bin: gacs.exe
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            bin: gacs.exe
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            bin: gacs
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            bin: gacs
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            bin: gacs
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            bin: gacs

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install Rust Nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly
        targets: ${{ matrix.target }}
        components: rust-src

    - name: Install Linux Cross-Compiler & Tools
      if: contains(matrix.target, 'linux') && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu

        if [ "${{ matrix.target }}" = "aarch64-unknown-linux-musl" ]; then
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        fi

        if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        fi

        if [ "${{ matrix.target }}" = "x86_64-unknown-linux-musl" ]; then
          echo "CC=musl-gcc" >> $GITHUB_ENV
        fi

    - name: Cargo Cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}

    - name: Run Build-Std
      env:
        RUSTFLAGS: "-Zunstable-options -Cpanic=immediate-abort"
      run: |
        cargo build -Z build-std=std,panic_abort -Z build-std-features="optimize_for_size" --release --target ${{ matrix.target }}

    - name: Prepare Artifact (Archive)
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release/

        if [ "${{ runner.os }}" = "Windows" ]; then
          7z a ../../../gacs-${{ matrix.target }}.zip ${{ matrix.bin }}
          echo "ARCHIVE_NAME=gacs-${{ matrix.target }}.zip" >> $GITHUB_ENV
        fi

        if [ "${{ runner.os }}" = "Linux" ]; then
          tar -czvf ../../../gacs-${{ matrix.target }}.tar.gz ${{ matrix.bin }}
          echo "ARCHIVE_NAME=gacs-${{ matrix.target }}.tar.gz" >> $GITHUB_ENV
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: binary-${{ matrix.target }}
        path: $ARCHIVE_NAME

  release:
    name: Create GitHub Release
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Download all artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: binary-*
        merge-multiple: true

    - name: Release to GitHub
      uses: softprops/action-gh-release@v3
      with:
        files: |
          gacs-*.zip
          gacs-*.tar.gz
        generate_release_notes: true
